In [26]:
import pandas as pd
import utils
import plotly.graph_objects as go
from constants.DPairs import DPair as PAIR
from constants.DFrequency import DFrequency as FREQ

In [27]:
pair = PAIR.EUR_USD
granularity = FREQ.H1

In [28]:
df = pd.read_pickle(utils.get_his_data_filename(pair, granularity))

In [29]:
non_cols = ['time', 'volume']

In [30]:
mod_cols = [x for x in df.columns if x not in non_cols]

In [31]:
df[mod_cols] = df[mod_cols].apply(pd.to_numeric)

In [32]:
df_plot = df.iloc[-100:].copy()

In [33]:
df_plot.shape

(100, 14)

In [40]:
fig = go.Figure()
fig.add_trace(go.Candlestick(
    x=df_plot.time, open=df_plot.mid_o, high=df_plot.mid_h, low=df_plot.mid_l, close=df_plot.mid_c, line=dict(width=1), opacity=1,

))
fig.update_layout(width=1000,height=400, margin=dict(l=10, r=10, b=10, t=10),
                  font=dict(size=12,color="#e1e1e1"),
                  paper_bgcolor="#1e1e1e", plot_bgcolor="#1e1e1e")
fig.update_xaxes(
    gridcolor="#1f292f", showgrid=True, fixedrange=True, rangeslider=dict(visible=False)
)
fig.update_yaxes(
    gridcolor="#1f292f", showgrid=True, fixedrange=True
)
fig.show()

In [ ]:
df.head()

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2025-09-23T05:00:00.000000000Z,3761,1.17976,1.18050,1.17950,1.17986,1.17967,1.18042,1.17942,1.17977,1.17984,1.18058,1.17957,1.17995
1,2025-09-23T06:00:00.000000000Z,6947,1.17985,1.18046,1.17901,1.17948,1.17977,1.18038,1.17892,1.17940,1.17993,1.18054,1.17909,1.17957
2,2025-09-23T07:00:00.000000000Z,13061,1.17948,1.18002,1.17790,1.17907,1.17940,1.17992,1.17777,1.17899,1.17956,1.18011,1.17800,1.17915
3,2025-09-23T08:00:00.000000000Z,9832,1.17906,1.18054,1.17840,1.18028,1.17898,1.18046,1.17833,1.18020,1.17915,1.18064,1.17848,1.18037
4,2025-09-23T09:00:00.000000000Z,6663,1.18030,1.18125,1.18005,1.18022,1.18022,1.18117,1.17997,1.18015,1.18038,1.18133,1.18013,1.18030

In [ ]:
df.describe()

,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,6094.074000,1.167929,1.168560,1.167312,1.167932,1.167834,1.168474,1.167219,1.167845,1.168024,1.168653,1.167398,1.168020
std,4593.113199,0.010892,0.010885,0.010878,0.010889,0.010891,0.010886,0.010878,0.010889,0.010892,0.010884,0.010878,0.010889
min,148.000000,1.142230,1.142280,1.141100,1.141660,1.142080,1.142190,1.141020,1.141560,1.142320,1.142360,1.141180,1.141770
25%,3086.750000,1.159737,1.160497,1.159130,1.159760,1.159640,1.160398,1.159048,1.159675,1.159850,1.160598,1.159210,1.159857
50%,4975.500000,1.167860,1.168420,1.167290,1.167860,1.167770,1.168345,1.167210,1.167780,1.167940,1.168525,1.167370,1.167935
75%,7774.250000,1.175327,1.175980,1.174820,1.175372,1.175250,1.175893,1.174713,1.175290,1.175455,1.176060,1.174910,1.175453
max,70503.000000,1.204300,1.208310,1.203720,1.204280,1.204140,1.208210,1.203530,1.204120,1.204450,1.208510,1.203880,1.204450

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    4000 non-null   str
 1   volume  4000 non-null   int64
 2   mid_o   4000 non-null   float64
 3   mid_h   4000 non-null   float64
 4   mid_l   4000 non-null   float64
 5   mid_c   4000 non-null   float64
 6   bid_o   4000 non-null   float64
 7   bid_h   4000 non-null   float64
 8   bid_l   4000 non-null   float64
 9   bid_c   4000 non-null   float64
 10  ask_o   4000 non-null   float64
 11  ask_h   4000 non-null   float64
 12  ask_l   4000 non-null   float64
 13  ask_c   4000 non-null   float64
dtypes: float64(12), int64(1), str(1)
memory usage: 437.6 KB

In [ ]:
non_cols = ['time', 'volume']

In [ ]:
mod_cols = [x for x in df.columns if x not in non_cols]

In [ ]:
df[mod_cols] = df[mod_cols].apply(pd.to_numeric)

In [ ]:
df

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2025-09-23T05:00:00.000000000Z,3761,1.17976,1.18050,1.17950,1.17986,1.17967,1.18042,1.17942,1.17977,1.17984,1.18058,1.17957,1.17995
1,2025-09-23T06:00:00.000000000Z,6947,1.17985,1.18046,1.17901,1.17948,1.17977,1.18038,1.17892,1.17940,1.17993,1.18054,1.17909,1.17957
2,2025-09-23T07:00:00.000000000Z,13061,1.17948,1.18002,1.17790,1.17907,1.17940,1.17992,1.17777,1.17899,1.17956,1.18011,1.17800,1.17915
3,2025-09-23T08:00:00.000000000Z,9832,1.17906,1.18054,1.17840,1.18028,1.17898,1.18046,1.17833,1.18020,1.17915,1.18064,1.17848,1.18037
4,2025-09-23T09:00:00.000000000Z,6663,1.18030,1.18125,1.18005,1.18022,1.18022,1.18117,1.17997,1.18015,1.18038,1.18133,1.18013,1.18030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,2026-05-15T16:00:00.000000000Z,5561,1.16266,1.16314,1.16232,1.16299,1.16257,1.16306,1.16224,1.16291,1.16274,1.16321,1.16240,1.16307
3996,2026-05-15T17:00:00.000000000Z,4627,1.16300,1.16356,1.16267,1.16268,1.16292,1.16348,1.16258,1.16261,1.16309,1.16365,1.16275,1.16276
3997,2026-05-15T18:00:00.000000000Z,4694,1.16269,1.16273,1.16170,1.16220,1.16262,1.16266,1.16162,1.16212,1.16276,1.16280,1.16178,1.16227
3998,2026-05-15T19:00:00.000000000Z,3406,1.16219,1.16232,1.16192,1.16214,1.16211,1.16224,1.16184,1.16206,1.16227,1.16240,1.16200,1.16223
3999,2026-05-15T20:00:00.000000000Z,2292,1.16214,1.16257,1.16194,1.16252,1.16207,1.16249,1.16185,1.16244,1.16222,1.16267,1.16202,1.16261

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    4000 non-null   str
 1   volume  4000 non-null   int64
 2   mid_o   4000 non-null   float64
 3   mid_h   4000 non-null   float64
 4   mid_l   4000 non-null   float64
 5   mid_c   4000 non-null   float64
 6   bid_o   4000 non-null   float64
 7   bid_h   4000 non-null   float64
 8   bid_l   4000 non-null   float64
 9   bid_c   4000 non-null   float64
 10  ask_o   4000 non-null   float64
 11  ask_h   4000 non-null   float64
 12  ask_l   4000 non-null   float64
 13  ask_c   4000 non-null   float64
dtypes: float64(12), int64(1), str(1)
memory usage: 437.6 KB

In [ ]:
df.describe()

,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,6094.074000,1.167929,1.168560,1.167312,1.167932,1.167834,1.168474,1.167219,1.167845,1.168024,1.168653,1.167398,1.168020
std,4593.113199,0.010892,0.010885,0.010878,0.010889,0.010891,0.010886,0.010878,0.010889,0.010892,0.010884,0.010878,0.010889
min,148.000000,1.142230,1.142280,1.141100,1.141660,1.142080,1.142190,1.141020,1.141560,1.142320,1.142360,1.141180,1.141770
25%,3086.750000,1.159737,1.160497,1.159130,1.159760,1.159640,1.160398,1.159048,1.159675,1.159850,1.160598,1.159210,1.159857
50%,4975.500000,1.167860,1.168420,1.167290,1.167860,1.167770,1.168345,1.167210,1.167780,1.167940,1.168525,1.167370,1.167935
75%,7774.250000,1.175327,1.175980,1.174820,1.175372,1.175250,1.175893,1.174713,1.175290,1.175455,1.176060,1.174910,1.175453
max,70503.000000,1.204300,1.208310,1.203720,1.204280,1.204140,1.208210,1.203530,1.204120,1.204450,1.208510,1.203880,1.204450