In [ ]:
import pandas as pd
import utils
import plotly.graph_objects as go
from constants.DPairs import DPair as PAIR
from constants.DFrequency import DFrequency as FREQ

In [5]:
pair = PAIR.EUR_USD
granularity = FREQ.H1

In [6]:
df = pd.read_pickle(utils.get_his_data_filename(pair, granularity))

In [7]:
df.head()

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2025-09-09T05:00:00.000000000Z,3676,1.17728,1.17801,1.17713,1.17788,1.17720,1.17794,1.17706,1.17780,1.17736,1.17809,1.17720,1.17796
1,2025-09-09T06:00:00.000000000Z,7293,1.17788,1.17799,1.17563,1.17650,1.17780,1.17791,1.17555,1.17641,1.17797,1.17807,1.17571,1.17658
2,2025-09-09T07:00:00.000000000Z,8574,1.17649,1.17686,1.17478,1.17526,1.17640,1.17678,1.17469,1.17519,1.17658,1.17694,1.17486,1.17534
3,2025-09-09T08:00:00.000000000Z,11915,1.17526,1.17624,1.17442,1.17595,1.17518,1.17617,1.17435,1.17587,1.17534,1.17633,1.17450,1.17603
4,2025-09-09T09:00:00.000000000Z,7592,1.17596,1.17724,1.17594,1.17676,1.17587,1.17717,1.17585,1.17669,1.17604,1.17732,1.17601,1.17683

In [8]:
df.describe()

             volume
count   4000.000000
mean    6129.734750
std     4708.536167
min      148.000000
25%     3084.250000
50%     4988.000000
75%     7784.750000
max    70503.000000

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    4000 non-null   str
 1   volume  4000 non-null   int64
 2   mid_o   4000 non-null   str
 3   mid_h   4000 non-null   str
 4   mid_l   4000 non-null   str
 5   mid_c   4000 non-null   str
 6   bid_o   4000 non-null   str
 7   bid_h   4000 non-null   str
 8   bid_l   4000 non-null   str
 9   bid_c   4000 non-null   str
 10  ask_o   4000 non-null   str
 11  ask_h   4000 non-null   str
 12  ask_l   4000 non-null   str
 13  ask_c   4000 non-null   str
dtypes: int64(1), str(13)
memory usage: 437.6 KB

In [11]:
non_cols = ['time', 'volume']

In [12]:
mod_cols = [x for x in df.columns if x not in non_cols]

In [14]:
df[mod_cols] = df[mod_cols].apply(pd.to_numeric)

In [15]:
df

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2025-09-09T05:00:00.000000000Z,3676,1.17728,1.17801,1.17713,1.17788,1.17720,1.17794,1.17706,1.17780,1.17736,1.17809,1.17720,1.17796
1,2025-09-09T06:00:00.000000000Z,7293,1.17788,1.17799,1.17563,1.17650,1.17780,1.17791,1.17555,1.17641,1.17797,1.17807,1.17571,1.17658
2,2025-09-09T07:00:00.000000000Z,8574,1.17649,1.17686,1.17478,1.17526,1.17640,1.17678,1.17469,1.17519,1.17658,1.17694,1.17486,1.17534
3,2025-09-09T08:00:00.000000000Z,11915,1.17526,1.17624,1.17442,1.17595,1.17518,1.17617,1.17435,1.17587,1.17534,1.17633,1.17450,1.17603
4,2025-09-09T09:00:00.000000000Z,7592,1.17596,1.17724,1.17594,1.17676,1.17587,1.17717,1.17585,1.17669,1.17604,1.17732,1.17601,1.17683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,2026-05-01T16:00:00.000000000Z,8895,1.17550,1.17572,1.17378,1.17382,1.17542,1.17564,1.17369,1.17374,1.17558,1.17581,1.17386,1.17390
3996,2026-05-01T17:00:00.000000000Z,5727,1.17382,1.17404,1.17293,1.17331,1.17374,1.17397,1.17285,1.17322,1.17391,1.17413,1.17300,1.17340
3997,2026-05-01T18:00:00.000000000Z,7115,1.17332,1.17342,1.17197,1.17274,1.17324,1.17333,1.17188,1.17265,1.17340,1.17350,1.17206,1.17282
3998,2026-05-01T19:00:00.000000000Z,3400,1.17274,1.17285,1.17178,1.17197,1.17266,1.17276,1.17171,1.17189,1.17282,1.17294,1.17185,1.17205
3999,2026-05-01T20:00:00.000000000Z,3074,1.17196,1.17228,1.17156,1.17212,1.17188,1.17217,1.17146,1.17198,1.17205,1.17252,1.17164,1.17227

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    4000 non-null   str
 1   volume  4000 non-null   int64
 2   mid_o   4000 non-null   float64
 3   mid_h   4000 non-null   float64
 4   mid_l   4000 non-null   float64
 5   mid_c   4000 non-null   float64
 6   bid_o   4000 non-null   float64
 7   bid_h   4000 non-null   float64
 8   bid_l   4000 non-null   float64
 9   bid_c   4000 non-null   float64
 10  ask_o   4000 non-null   float64
 11  ask_h   4000 non-null   float64
 12  ask_l   4000 non-null   float64
 13  ask_c   4000 non-null   float64
dtypes: float64(12), int64(1), str(1)
memory usage: 437.6 KB

In [17]:
df.describe()

,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,6129.734750,1.168166,1.168806,1.167542,1.168172,1.168072,1.168721,1.167449,1.168085,1.168261,1.168899,1.167628,1.168260
std,4708.536167,0.011050,0.011050,0.011033,0.011047,0.011050,0.011051,0.011033,0.011048,0.011051,0.011049,0.011033,0.011047
min,148.000000,1.142230,1.142280,1.141100,1.141660,1.142080,1.142190,1.141020,1.141560,1.142320,1.142360,1.141180,1.141770
25%,3084.250000,1.159737,1.160497,1.159130,1.159760,1.159640,1.160398,1.159048,1.159675,1.159850,1.160598,1.159210,1.159857
50%,4988.000000,1.168215,1.168875,1.167600,1.168225,1.168105,1.168775,1.167520,1.168145,1.168305,1.168965,1.167690,1.168300
75%,7784.750000,1.176020,1.176645,1.175453,1.176020,1.175943,1.176560,1.175345,1.175940,1.176115,1.176743,1.175540,1.176102
max,70503.000000,1.204300,1.208310,1.203720,1.204280,1.204140,1.208210,1.203530,1.204120,1.204450,1.208510,1.203880,1.204450