In [1]:
import pandas as pd
import utils
import plotly.graph_objects as go
from constants.DPairs import DPair as PAIR
from constants.DFrequency import DFrequency as FREQ

In [2]:
pair = PAIR.EUR_USD
granularity = FREQ.H1

In [3]:
df = pd.read_pickle(utils.get_his_data_filename(pair, granularity))

In [4]:
non_cols = ['time', 'volume']

In [5]:
mod_cols = [x for x in df.columns if x not in non_cols]

In [6]:
df[mod_cols] = df[mod_cols].apply(pd.to_numeric)

In [7]:
df_plot = df.iloc[-100:].copy()

In [8]:
df_plot.shape

(100, 14)

In [ ]:
fig = go.Figure()
fig.add_trace(go.Candlestick(
    x=df_plot.time, open=df_plot.mid_o, high=df_plot.mid_h, low=df_plot.mid_l, close=df_plot.mid_c, 
))
fig.show()

In [10]:
df.head()

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2025-09-16T05:00:00.000000000Z,3638,1.17771,1.17803,1.17736,1.17781,1.17763,1.17796,1.17729,1.17773,1.17779,1.17811,1.17743,1.17789
1,2025-09-16T06:00:00.000000000Z,7663,1.17783,1.17914,1.17777,1.17874,1.17775,1.17906,1.17770,1.17866,1.17791,1.17923,1.17784,1.17882
2,2025-09-16T07:00:00.000000000Z,8239,1.17874,1.18020,1.17864,1.17944,1.17866,1.18012,1.17857,1.17936,1.17881,1.18028,1.17871,1.17952
3,2025-09-16T08:00:00.000000000Z,7218,1.17942,1.18038,1.17902,1.17950,1.17934,1.18031,1.17894,1.17943,1.17951,1.18046,1.17909,1.17958
4,2025-09-16T09:00:00.000000000Z,8589,1.17952,1.18182,1.17951,1.18141,1.17943,1.18175,1.17943,1.18134,1.17962,1.18189,1.17959,1.18148

In [11]:
df.describe()

,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,6150.057000,1.168178,1.168818,1.167556,1.168185,1.168083,1.168732,1.167463,1.168097,1.168273,1.168911,1.167642,1.168272
std,4690.394218,0.011059,0.011059,0.011042,0.011057,0.011059,0.011060,0.011042,0.011057,0.011060,0.011058,0.011042,0.011057
min,148.000000,1.142230,1.142280,1.141100,1.141660,1.142080,1.142190,1.141020,1.141560,1.142320,1.142360,1.141180,1.141770
25%,3102.750000,1.159737,1.160497,1.159130,1.159760,1.159640,1.160398,1.159048,1.159675,1.159850,1.160598,1.159210,1.159857
50%,5017.500000,1.168195,1.168830,1.167610,1.168205,1.168100,1.168740,1.167525,1.168120,1.168290,1.168935,1.167695,1.168285
75%,7830.500000,1.176120,1.176790,1.175510,1.176133,1.176032,1.176710,1.175390,1.176055,1.176210,1.176870,1.175593,1.176213
max,70503.000000,1.204300,1.208310,1.203720,1.204280,1.204140,1.208210,1.203530,1.204120,1.204450,1.208510,1.203880,1.204450

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    4000 non-null   str
 1   volume  4000 non-null   int64
 2   mid_o   4000 non-null   float64
 3   mid_h   4000 non-null   float64
 4   mid_l   4000 non-null   float64
 5   mid_c   4000 non-null   float64
 6   bid_o   4000 non-null   float64
 7   bid_h   4000 non-null   float64
 8   bid_l   4000 non-null   float64
 9   bid_c   4000 non-null   float64
 10  ask_o   4000 non-null   float64
 11  ask_h   4000 non-null   float64
 12  ask_l   4000 non-null   float64
 13  ask_c   4000 non-null   float64
dtypes: float64(12), int64(1), str(1)
memory usage: 437.6 KB

In [13]:
non_cols = ['time', 'volume']

In [14]:
mod_cols = [x for x in df.columns if x not in non_cols]

In [15]:
df[mod_cols] = df[mod_cols].apply(pd.to_numeric)

In [16]:
df

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2025-09-16T05:00:00.000000000Z,3638,1.17771,1.17803,1.17736,1.17781,1.17763,1.17796,1.17729,1.17773,1.17779,1.17811,1.17743,1.17789
1,2025-09-16T06:00:00.000000000Z,7663,1.17783,1.17914,1.17777,1.17874,1.17775,1.17906,1.17770,1.17866,1.17791,1.17923,1.17784,1.17882
2,2025-09-16T07:00:00.000000000Z,8239,1.17874,1.18020,1.17864,1.17944,1.17866,1.18012,1.17857,1.17936,1.17881,1.18028,1.17871,1.17952
3,2025-09-16T08:00:00.000000000Z,7218,1.17942,1.18038,1.17902,1.17950,1.17934,1.18031,1.17894,1.17943,1.17951,1.18046,1.17909,1.17958
4,2025-09-16T09:00:00.000000000Z,8589,1.17952,1.18182,1.17951,1.18141,1.17943,1.18175,1.17943,1.18134,1.17962,1.18189,1.17959,1.18148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,2026-05-08T16:00:00.000000000Z,4692,1.17728,1.17786,1.17708,1.17712,1.17720,1.17778,1.17701,1.17705,1.17736,1.17795,1.17716,1.17719
3996,2026-05-08T17:00:00.000000000Z,3132,1.17712,1.17763,1.17706,1.17724,1.17705,1.17755,1.17698,1.17717,1.17720,1.17771,1.17715,1.17731
3997,2026-05-08T18:00:00.000000000Z,5062,1.17723,1.17818,1.17708,1.17786,1.17716,1.17810,1.17701,1.17778,1.17730,1.17826,1.17715,1.17795
3998,2026-05-08T19:00:00.000000000Z,3764,1.17786,1.17832,1.17770,1.17802,1.17778,1.17825,1.17763,1.17795,1.17794,1.17840,1.17777,1.17810
3999,2026-05-08T20:00:00.000000000Z,2514,1.17803,1.17881,1.17790,1.17852,1.17795,1.17872,1.17781,1.17838,1.17811,1.17893,1.17798,1.17865

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    4000 non-null   str
 1   volume  4000 non-null   int64
 2   mid_o   4000 non-null   float64
 3   mid_h   4000 non-null   float64
 4   mid_l   4000 non-null   float64
 5   mid_c   4000 non-null   float64
 6   bid_o   4000 non-null   float64
 7   bid_h   4000 non-null   float64
 8   bid_l   4000 non-null   float64
 9   bid_c   4000 non-null   float64
 10  ask_o   4000 non-null   float64
 11  ask_h   4000 non-null   float64
 12  ask_l   4000 non-null   float64
 13  ask_c   4000 non-null   float64
dtypes: float64(12), int64(1), str(1)
memory usage: 437.6 KB

In [18]:
df.describe()

,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,6150.057000,1.168178,1.168818,1.167556,1.168185,1.168083,1.168732,1.167463,1.168097,1.168273,1.168911,1.167642,1.168272
std,4690.394218,0.011059,0.011059,0.011042,0.011057,0.011059,0.011060,0.011042,0.011057,0.011060,0.011058,0.011042,0.011057
min,148.000000,1.142230,1.142280,1.141100,1.141660,1.142080,1.142190,1.141020,1.141560,1.142320,1.142360,1.141180,1.141770
25%,3102.750000,1.159737,1.160497,1.159130,1.159760,1.159640,1.160398,1.159048,1.159675,1.159850,1.160598,1.159210,1.159857
50%,5017.500000,1.168195,1.168830,1.167610,1.168205,1.168100,1.168740,1.167525,1.168120,1.168290,1.168935,1.167695,1.168285
75%,7830.500000,1.176120,1.176790,1.175510,1.176133,1.176032,1.176710,1.175390,1.176055,1.176210,1.176870,1.175593,1.176213
max,70503.000000,1.204300,1.208310,1.203720,1.204280,1.204140,1.208210,1.203530,1.204120,1.204450,1.208510,1.203880,1.204450